[package]
name = "twemoji-assets"
version = "0.1.0+14.0.2"
edition = "2021"

[features]
default = ["svg", "names"]
svg = []
png = []
names = []

[workspace]
members = ["examples"]

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "from_emoji"
harness = false
